services:
  pyro4_naming:
    build:
      context: .
      dockerfile: Dockerfile.pyro4_naming
    container_name: pyro4_naming
    network_mode: "host"

  pyroserver:
    build:
      context: .
      dockerfile: Dockerfile.pyroserver
    container_name: pyroserver
    depends_on:
      - pyro4_naming
    network_mode: "host"

  socketserver:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mysocketserver
    depends_on:
      - pyroserver
    network_mode: "host"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: myclient
    depends_on:
      - socketserver
    network_mode: "host"
